package com.udianqu.wash.model;

public class Auto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.user_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.pn
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String pn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.brand
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.model
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.color
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auto.default_region_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer defaultRegionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.id
     *
     * @return the value of t_auto.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.id
     *
     * @param id the value for t_auto.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.user_id
     *
     * @return the value of t_auto.user_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.user_id
     *
     * @param userId the value for t_auto.user_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.pn
     *
     * @return the value of t_auto.pn
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.pn
     *
     * @param pn the value for t_auto.pn
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setPn(String pn) {
        this.pn = pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.brand
     *
     * @return the value of t_auto.brand
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.brand
     *
     * @param brand the value for t_auto.brand
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.model
     *
     * @return the value of t_auto.model
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.model
     *
     * @param model the value for t_auto.model
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.color
     *
     * @return the value of t_auto.color
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.color
     *
     * @param color the value for t_auto.color
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auto.default_region_id
     *
     * @return the value of t_auto.default_region_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getDefaultRegionId() {
        return defaultRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auto.default_region_id
     *
     * @param defaultRegionId the value for t_auto.default_region_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setDefaultRegionId(Integer defaultRegionId) {
        this.defaultRegionId = defaultRegionId;
    }
}