package com.udianqu.wash.model;

public class BillSerial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_serial.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_serial.bill_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer billTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_serial.ymd
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer ymd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_serial.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_serial.no_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer noLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_serial.value
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_serial.id
     *
     * @return the value of t_bill_serial.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_serial.id
     *
     * @param id the value for t_bill_serial.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_serial.bill_type_id
     *
     * @return the value of t_bill_serial.bill_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getBillTypeId() {
        return billTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_serial.bill_type_id
     *
     * @param billTypeId the value for t_bill_serial.bill_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setBillTypeId(Integer billTypeId) {
        this.billTypeId = billTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_serial.ymd
     *
     * @return the value of t_bill_serial.ymd
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getYmd() {
        return ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_serial.ymd
     *
     * @param ymd the value for t_bill_serial.ymd
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setYmd(Integer ymd) {
        this.ymd = ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_serial.prefix
     *
     * @return the value of t_bill_serial.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_serial.prefix
     *
     * @param prefix the value for t_bill_serial.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_serial.no_length
     *
     * @return the value of t_bill_serial.no_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getNoLength() {
        return noLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_serial.no_length
     *
     * @param noLength the value for t_bill_serial.no_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setNoLength(Integer noLength) {
        this.noLength = noLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_serial.value
     *
     * @return the value of t_bill_serial.value
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_serial.value
     *
     * @param value the value for t_bill_serial.value
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}