package com.udianqu.wash.model;

public class BillType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_type.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_type.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_type.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_type.no_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Byte noLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_type.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_type.id
     *
     * @return the value of t_bill_type.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_type.id
     *
     * @param id the value for t_bill_type.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_type.name
     *
     * @return the value of t_bill_type.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_type.name
     *
     * @param name the value for t_bill_type.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_type.prefix
     *
     * @return the value of t_bill_type.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_type.prefix
     *
     * @param prefix the value for t_bill_type.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_type.no_length
     *
     * @return the value of t_bill_type.no_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Byte getNoLength() {
        return noLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_type.no_length
     *
     * @param noLength the value for t_bill_type.no_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setNoLength(Byte noLength) {
        this.noLength = noLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_type.note
     *
     * @return the value of t_bill_type.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_type.note
     *
     * @param note the value for t_bill_type.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }
}