package com.udianqu.wash.model;

import java.util.Date;

public class CouponType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_type.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_type.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_type.period_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Byte periodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_type.begin_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_type.end_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_type.month
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer month;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_type.id
     *
     * @return the value of t_coupon_type.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_type.id
     *
     * @param id the value for t_coupon_type.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_type.name
     *
     * @return the value of t_coupon_type.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_type.name
     *
     * @param name the value for t_coupon_type.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_type.period_type
     *
     * @return the value of t_coupon_type.period_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Byte getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_type.period_type
     *
     * @param periodType the value for t_coupon_type.period_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPeriodType(Byte periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_type.begin_time
     *
     * @return the value of t_coupon_type.begin_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_type.begin_time
     *
     * @param beginTime the value for t_coupon_type.begin_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_type.end_time
     *
     * @return the value of t_coupon_type.end_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_type.end_time
     *
     * @param endTime the value for t_coupon_type.end_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_type.month
     *
     * @return the value of t_coupon_type.month
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_type.month
     *
     * @param month the value for t_coupon_type.month
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setMonth(Integer month) {
        this.month = month;
    }
}