package com.udianqu.wash.model;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.coupon_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer couponTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.user_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.period_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Byte periodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.begin_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.end_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.month
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.is_validity
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Boolean isValidity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.id
     *
     * @return the value of t_coupon.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.id
     *
     * @param id the value for t_coupon.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.coupon_type_id
     *
     * @return the value of t_coupon.coupon_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getCouponTypeId() {
        return couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.coupon_type_id
     *
     * @param couponTypeId the value for t_coupon.coupon_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setCouponTypeId(Integer couponTypeId) {
        this.couponTypeId = couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.user_id
     *
     * @return the value of t_coupon.user_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.user_id
     *
     * @param userId the value for t_coupon.user_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.period_type
     *
     * @return the value of t_coupon.period_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Byte getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.period_type
     *
     * @param periodType the value for t_coupon.period_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPeriodType(Byte periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.begin_time
     *
     * @return the value of t_coupon.begin_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.begin_time
     *
     * @param beginTime the value for t_coupon.begin_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.end_time
     *
     * @return the value of t_coupon.end_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.end_time
     *
     * @param endTime the value for t_coupon.end_time
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.month
     *
     * @return the value of t_coupon.month
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.month
     *
     * @param month the value for t_coupon.month
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.is_validity
     *
     * @return the value of t_coupon.is_validity
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Boolean getIsValidity() {
        return isValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.is_validity
     *
     * @param isValidity the value for t_coupon.is_validity
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setIsValidity(Boolean isValidity) {
        this.isValidity = isValidity;
    }
}