package com.udianqu.wash.model;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.pid
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.level
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.path
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.bm_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer bmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.sort
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.is_shop
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Boolean isShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.is_used
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Boolean isUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.id
     *
     * @return the value of t_org.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.id
     *
     * @param id the value for t_org.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.name
     *
     * @return the value of t_org.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.name
     *
     * @param name the value for t_org.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.pid
     *
     * @return the value of t_org.pid
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.pid
     *
     * @param pid the value for t_org.pid
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.level
     *
     * @return the value of t_org.level
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.level
     *
     * @param level the value for t_org.level
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.path
     *
     * @return the value of t_org.path
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.path
     *
     * @param path the value for t_org.path
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.bm_id
     *
     * @return the value of t_org.bm_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getBmId() {
        return bmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.bm_id
     *
     * @param bmId the value for t_org.bm_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setBmId(Integer bmId) {
        this.bmId = bmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.sort
     *
     * @return the value of t_org.sort
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.sort
     *
     * @param sort the value for t_org.sort
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.note
     *
     * @return the value of t_org.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.note
     *
     * @param note the value for t_org.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.is_shop
     *
     * @return the value of t_org.is_shop
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Boolean getIsShop() {
        return isShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.is_shop
     *
     * @param isShop the value for t_org.is_shop
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setIsShop(Boolean isShop) {
        this.isShop = isShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.is_used
     *
     * @return the value of t_org.is_used
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.is_used
     *
     * @param isUsed the value for t_org.is_used
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }
}