package com.udianqu.wash.model;

public class Parameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parameter.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parameter.key
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parameter.value
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parameter.id
     *
     * @return the value of t_parameter.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parameter.id
     *
     * @param id the value for t_parameter.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parameter.key
     *
     * @return the value of t_parameter.key
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parameter.key
     *
     * @param key the value for t_parameter.key
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parameter.value
     *
     * @return the value of t_parameter.value
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parameter.value
     *
     * @param value the value for t_parameter.value
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setValue(String value) {
        this.value = value;
    }
}