package com.udianqu.wash.model;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.order_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.url
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.id
     *
     * @return the value of t_picture.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.id
     *
     * @param id the value for t_picture.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.order_id
     *
     * @return the value of t_picture.order_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.order_id
     *
     * @param orderId the value for t_picture.order_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.url
     *
     * @return the value of t_picture.url
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.url
     *
     * @param url the value for t_picture.url
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.note
     *
     * @return the value of t_picture.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.note
     *
     * @param note the value for t_picture.note
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }
}