package com.udianqu.wash.model;

public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.name
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.pid
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.level
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.path
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.is_estate
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Boolean isEstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.address
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.shop_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.sort
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.id
     *
     * @return the value of t_region.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.id
     *
     * @param id the value for t_region.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.name
     *
     * @return the value of t_region.name
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.name
     *
     * @param name the value for t_region.name
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.pid
     *
     * @return the value of t_region.pid
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.pid
     *
     * @param pid the value for t_region.pid
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.level
     *
     * @return the value of t_region.level
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.level
     *
     * @param level the value for t_region.level
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.path
     *
     * @return the value of t_region.path
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.path
     *
     * @param path the value for t_region.path
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.is_estate
     *
     * @return the value of t_region.is_estate
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Boolean getIsEstate() {
        return isEstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.is_estate
     *
     * @param isEstate the value for t_region.is_estate
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setIsEstate(Boolean isEstate) {
        this.isEstate = isEstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.address
     *
     * @return the value of t_region.address
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.address
     *
     * @param address the value for t_region.address
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.shop_id
     *
     * @return the value of t_region.shop_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.shop_id
     *
     * @param shopId the value for t_region.shop_id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.sort
     *
     * @return the value of t_region.sort
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.sort
     *
     * @param sort the value for t_region.sort
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}