package com.udianqu.wash.model;

public class SerialRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_serial_rule.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_serial_rule.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_serial_rule.org_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_serial_rule.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_serial_rule.middle_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer middleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_serial_rule.number_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Byte numberLength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_serial_rule.id
     *
     * @return the value of t_serial_rule.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_serial_rule.id
     *
     * @param id the value for t_serial_rule.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_serial_rule.name
     *
     * @return the value of t_serial_rule.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_serial_rule.name
     *
     * @param name the value for t_serial_rule.name
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_serial_rule.org_id
     *
     * @return the value of t_serial_rule.org_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_serial_rule.org_id
     *
     * @param orgId the value for t_serial_rule.org_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_serial_rule.prefix
     *
     * @return the value of t_serial_rule.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_serial_rule.prefix
     *
     * @param prefix the value for t_serial_rule.prefix
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_serial_rule.middle_type
     *
     * @return the value of t_serial_rule.middle_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getMiddleType() {
        return middleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_serial_rule.middle_type
     *
     * @param middleType the value for t_serial_rule.middle_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setMiddleType(Integer middleType) {
        this.middleType = middleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_serial_rule.number_length
     *
     * @return the value of t_serial_rule.number_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Byte getNumberLength() {
        return numberLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_serial_rule.number_length
     *
     * @param numberLength the value for t_serial_rule.number_length
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setNumberLength(Byte numberLength) {
        this.numberLength = numberLength;
    }
}