package com.udianqu.wash.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserBalance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance.id
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance.user_id
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance.type
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance.record_time
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    private Date recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance.amount
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    private BigDecimal amount;
    private String orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance.id
     *
     * @return the value of t_user_balance.id
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    
    public Integer getId() {
        return id;
    }

    public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance.id
     *
     * @param id the value for t_user_balance.id
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance.user_id
     *
     * @return the value of t_user_balance.user_id
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance.user_id
     *
     * @param userId the value for t_user_balance.user_id
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance.type
     *
     * @return the value of t_user_balance.type
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance.type
     *
     * @param type the value for t_user_balance.type
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance.record_time
     *
     * @return the value of t_user_balance.record_time
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance.record_time
     *
     * @param recordTime the value for t_user_balance.record_time
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance.amount
     *
     * @return the value of t_user_balance.amount
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance.amount
     *
     * @param amount the value for t_user_balance.amount
     *
     * @mbggenerated Sat Sep 19 17:39:11 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}