package com.udianqu.wash.model;

import java.math.BigDecimal;

public class WashOrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.order_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.wash_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer washTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.coupon_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.coupon_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private BigDecimal couponAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.fixed_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private BigDecimal fixedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_order_item.final_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    private BigDecimal finalAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.id
     *
     * @return the value of t_wash_order_item.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.id
     *
     * @param id the value for t_wash_order_item.id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.order_id
     *
     * @return the value of t_wash_order_item.order_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.order_id
     *
     * @param orderId the value for t_wash_order_item.order_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.wash_type_id
     *
     * @return the value of t_wash_order_item.wash_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getWashTypeId() {
        return washTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.wash_type_id
     *
     * @param washTypeId the value for t_wash_order_item.wash_type_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setWashTypeId(Integer washTypeId) {
        this.washTypeId = washTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.coupon_id
     *
     * @return the value of t_wash_order_item.coupon_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.coupon_id
     *
     * @param couponId the value for t_wash_order_item.coupon_id
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.coupon_amount
     *
     * @return the value of t_wash_order_item.coupon_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.coupon_amount
     *
     * @param couponAmount the value for t_wash_order_item.coupon_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.fixed_amount
     *
     * @return the value of t_wash_order_item.fixed_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public BigDecimal getFixedAmount() {
        return fixedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.fixed_amount
     *
     * @param fixedAmount the value for t_wash_order_item.fixed_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setFixedAmount(BigDecimal fixedAmount) {
        this.fixedAmount = fixedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_order_item.final_amount
     *
     * @return the value of t_wash_order_item.final_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public BigDecimal getFinalAmount() {
        return finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_order_item.final_amount
     *
     * @param finalAmount the value for t_wash_order_item.final_amount
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    public void setFinalAmount(BigDecimal finalAmount) {
        this.finalAmount = finalAmount;
    }
}