package com.udianqu.wash.model;

import java.math.BigDecimal;

public class WashType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.name
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.amount
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.note
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.need_key
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Boolean needKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.sort
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Byte sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wash_type.is_used
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    private Boolean isUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.id
     *
     * @return the value of t_wash_type.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.id
     *
     * @param id the value for t_wash_type.id
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.name
     *
     * @return the value of t_wash_type.name
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.name
     *
     * @param name the value for t_wash_type.name
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.amount
     *
     * @return the value of t_wash_type.amount
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.amount
     *
     * @param amount the value for t_wash_type.amount
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.note
     *
     * @return the value of t_wash_type.note
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.note
     *
     * @param note the value for t_wash_type.note
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.need_key
     *
     * @return the value of t_wash_type.need_key
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Boolean getNeedKey() {
        return needKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.need_key
     *
     * @param needKey the value for t_wash_type.need_key
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setNeedKey(Boolean needKey) {
        this.needKey = needKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.sort
     *
     * @return the value of t_wash_type.sort
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.sort
     *
     * @param sort the value for t_wash_type.sort
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wash_type.is_used
     *
     * @return the value of t_wash_type.is_used
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wash_type.is_used
     *
     * @param isUsed the value for t_wash_type.is_used
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }
}