package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.Auto;
import com.udianqu.wash.model.AutoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface AutoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int countByExample(AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int deleteByExample(AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int insert(Auto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int insertSelective(Auto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    List<Auto> selectByExample(AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    Auto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") Auto record, @Param("example") AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int updateByExample(@Param("record") Auto record, @Param("example") AutoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int updateByPrimaryKeySelective(Auto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auto
     *
     * @mbggenerated Fri Jul 17 15:46:12 CST 2015
     */
    int updateByPrimaryKey(Auto record);
}