package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.BillType;
import com.udianqu.wash.model.BillTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface BillTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(BillTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(BillTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(BillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(BillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<BillType> selectByExample(BillTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    BillType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillType record, @Param("example") BillTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") BillType record, @Param("example") BillTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(BillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(BillType record);
}