package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.BillSerial;
import com.udianqu.wash.model.BillSerialExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface BillSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(BillSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(BillSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(BillSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(BillSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<BillSerial> selectByExample(BillSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    BillSerial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillSerial record, @Param("example") BillSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") BillSerial record, @Param("example") BillSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(BillSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_serial
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(BillSerial record);

	String getNextBillSerialNo(Map<String, Object> map);
	String updateBillSerialNo(Map<String,Object> map);
}