package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.CouponType;
import com.udianqu.wash.model.CouponTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface CouponTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(CouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(CouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<CouponType> selectByExample(CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    CouponType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") CouponType record, @Param("example") CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") CouponType record, @Param("example") CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(CouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(CouponType record);
}