package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.Pay;
import com.udianqu.wash.model.PayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<Pay> selectByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    Pay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(Pay record);
}