package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.SerialRule;
import com.udianqu.wash.model.SerialRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface SerialRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(SerialRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(SerialRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(SerialRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(SerialRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<SerialRule> selectByExample(SerialRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    SerialRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") SerialRule record, @Param("example") SerialRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") SerialRule record, @Param("example") SerialRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(SerialRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_serial_rule
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(SerialRule record);
}