package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.WashType;
import com.udianqu.wash.model.WashTypeExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface WashTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(WashTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(WashTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(WashType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(WashType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<WashType> selectByExample(WashTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    WashType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") WashType record, @Param("example") WashTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") WashType record, @Param("example") WashTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(WashType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_type
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(WashType record);

	List<WashType> loadWashTypeListWithPage(Map<String, Object> map);

	int countByMap(Map<String, Object> map);
}