package com.udianqu.wash.dao;

import com.udianqu.wash.core.MyBatisRepository;
import com.udianqu.wash.model.WashOrderItem;
import com.udianqu.wash.model.WashOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface WashOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int countByExample(WashOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByExample(WashOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insert(WashOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int insertSelective(WashOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    List<WashOrderItem> selectByExample(WashOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    WashOrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") WashOrderItem record, @Param("example") WashOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByExample(@Param("record") WashOrderItem record, @Param("example") WashOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKeySelective(WashOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wash_order_item
     *
     * @mbggenerated Mon Jul 20 12:31:35 CST 2015
     */
    int updateByPrimaryKey(WashOrderItem record);
}